version: "3.1"
services:
  tls-client:
    image: englert/tls-client
    container_name: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
      args:
        JAR_FILE: tlsclient/target/tls-client-1.0-SNAPSHOT.jar
        PROJ_ROOT: client
    ports:
      - "8081:8080"
    links:
      - "nginx-server:test.local"
#    volumes:
#      - ./client/certs:/etc/certs
  nginx-server:
    image: englert/tls-server
    container_name: server
    build: ./server
    ports:
      - "8090:443"
      - "8089:80"
    volumes:
      - ./server/html:/var/www/html/
      - ./server/certs:/etc/nginx/certs
